<?php

/**
 * Shopgate GmbH
 *
 * URHEBERRECHTSHINWEIS
 *
 * Dieses Plugin ist urheberrechtlich geschützt. Es darf ausschließlich von Kunden der Shopgate GmbH
 * zum Zwecke der eigenen Kommunikation zwischen dem IT-System des Kunden mit dem IT-System der
 * Shopgate GmbH über www.shopgate.com verwendet werden. Eine darüber hinausgehende Vervielfältigung, Verbreitung,
 * öffentliche Zugänglichmachung, Bearbeitung oder Weitergabe an Dritte ist nur mit unserer vorherigen
 * schriftlichen Zustimmung zulässig. Die Regelungen der §§ 69 d Abs. 2, 3 und 69 e UrhG bleiben hiervon unberührt.
 *
 * COPYRIGHT NOTICE
 *
 * This plugin is the subject of copyright protection. It is only for the use of Shopgate GmbH customers,
 * for the purpose of facilitating communication between the IT system of the customer and the IT system
 * of Shopgate GmbH via www.shopgate.com. Any reproduction, dissemination, public propagation, processing or
 * transfer to third parties is only permitted where we previously consented thereto in writing. The provisions
 * of paragraph 69 d, sub-paragraphs 2, 3 and paragraph 69, sub-paragraph e of the German Copyright Act shall remain unaffected.
 *
 * @author Shopgate GmbH <interfaces@shopgate.com>
 */

/** @var Shopgate_Framework_Block_Payment_MobilePayment $this */
$shopgateOrder  = $this->getShopgateOrder();
$shopgateObject = $shopgateOrder->getShopgateOrderObject();

if (!$shopgateOrder->getId() || empty($shopgateObject)):
    echo $this->printHtmlError($this->__('Error importing order information: please contact Shopgate'));
endif;

if (!empty($shopgateObject) && $shopgateObject->getIsTest()):
    echo $this->printHtmlError($this->__('## This order is a TEST by Shopgate - DO NOT SHIP!'));
endif;

if ($this->hasDifferentPrices()):
    echo $this->printHtmlError(
        $this->__(
            '!! The total amount in Magento differs from the total amount at Shopgate. Please check your tax settings.'
        )
    );
endif;

if ($shopgateOrder->getIsShippingBlocked()):
    echo $this->printHtmlError($this->__('## Note: Shipping of this order is blocked by Shopgate!'));
endif;

if ($shopgateOrder->getIsCustomerInvoiceBlocked()):
    echo $this->__('## Note: For this order you must not create an invoice!');
endif;

echo $this->__('Shopgate order number: %s', $shopgateOrder->getShopgateOrderNumber()); ?>
<p style="margin-top: 1em;">
    <?php echo $this->printPaymentInfo($this->getPaymentInfos()); ?>
</p>